id: 29e15c7fd8e14b6d9d67bca0d9c0bf72
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_114-The_King_of_the_Array_of_All_Dharmas-v1
  language: en
  author: ''
  volume: {}
